"""initial schema

Revision ID: 20260602_0001
Revises:
Create Date: 2026-06-02
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "20260602_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Physical tables were created directly in open_deep_research for this phase.
    # Future migrations should be autogenerated from src.web_app.models.orm.
    pass


def downgrade() -> None:
    pass
