import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'

import * as artifacts from '../api/artifacts'
import type { Artifact } from '../api/types'
import { EmptyState } from '../components/common/EmptyState'
import { ErrorState } from '../components/common/ErrorState'
import { JsonBlock } from '../components/common/JsonBlock'
import { LoadingState } from '../components/common/LoadingState'
import { PageHeader } from '../components/common/PageHeader'
import { StatusPill } from '../components/common/StatusPill'

export function ArtifactsPage() {
  const [params] = useSearchParams()
  const [items, setItems] = useState<Artifact[]>([])
  const [selected, setSelected] = useState<Artifact | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    artifacts.list().then(async (list) => {
      setItems(list)
      const selectedId = params.get('artifactId') || list[0]?.id
      if (selectedId) setSelected(await artifacts.get(selectedId))
    }).catch((exc) => setError(exc.message)).finally(() => setLoading(false))
  }, [params])

  return (
    <>
      <PageHeader title="Artifacts" description="Local outputs generated by research, tools, and Agent runs. Viewing only, no editing in this MVP." />
      {error ? <ErrorState message={error} /> : loading ? <LoadingState /> : !items.length ? <EmptyState title="No Artifacts yet" /> : (
        <div className="split">
          <div className="stack">{items.map((item) => <button className="card" key={item.id} onClick={() => artifacts.get(item.id).then(setSelected)}><strong>{item.title}</strong><p><StatusPill value={item.artifact_type} /> <span className="mono small">#{item.id}</span></p></button>)}</div>
          <aside className="panel stack"><h2>{selected?.title || 'Select artifact'}</h2><JsonBlock value={selected} /></aside>
        </div>
      )}
    </>
  )
}
